version: '3.8'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Senha#1234"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - cadfuncionario-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P 'Senha#1234' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20

  api:
    build:
      context: .
      dockerfile: CadFuncionario.API/Dockerfile
    container_name: cadfuncionario-api
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5005:5005"
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=EmpresaDB;User Id=sa;Password=Senha#1234;TrustServerCertificate=True"
    networks:
      - cadfuncionario-network

  frontend:
    build:
      context: ../cadfuncionario-frontend
      dockerfile: Dockerfile
    container_name: cadfuncionario-frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - cadfuncionario-network

networks:
  cadfuncionario-network:
    driver: bridge

volumes:
  sqlserver-data: